# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run character yatta

on:
  schedule:
    - cron:  '30 0 * * *'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd crawler
        pip install -r requirements.txt
        sudo apt update
        sudo apt install -y jq
    - name: Run
      run: |
        cd crawler
        for c in $(cat ../lib/characterlist.json| jq -r '.data[]|select(.spoiler==true)|.ENname' | sed s'/(WIP)//g' | sed s'/ /-/'); do
          python character_yatta.py $c
        done
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y tree jq
    - name: Check result
      run: |
        tree crawler/yatta
        for c in $(cat ../lib/characterlist.json| jq -r '.data[]|select(.spoiler==true)|.ENname' | sed s'/(WIP)//g' | sed s'/ /-/'); do
          diff crawler/yatta/lib/${c}.json lib/${c}.json
        done
