# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run-lightcone-yatta

on:
  schedule:
    - cron:  '40 0 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd crawler
        pip install -r requirements.txt
    - name: Run
      run: |
        cd ${GITHUB_WORKSPACE}/crawler
        tree
        for c in $(cat ../lib/lightconelist.json| jq -r '.data[]|select(.spoiler==true)|.ENname' | sed s'/(WIP)//g' | sed s'/ /-/'); do
          python lightcone_yatta.py ${c,,}
          echo '------------------------------------------------'
        done
    - name: Check result
      run: |
        cd ${GITHUB_WORKSPACE}/crawler
        tree yatta
        for c in $(cat ../lib/lightconelist.json| jq -r '.data[]|select(.spoiler==true)|.id' | sed s'/(WIP)//g' | sed s'/ /-/'); do
          echo -e "\033[32mdiff yatta/lib/lightcones/${c,,}.json ../lib/lightcones/${c,,}.json\033[0m"
          (diff yatta/lib/lightcones/${c,,}.json ../lib/lightcones/${c,,}.json) || true
          echo '------------------------------------------------'
        done
        exit 0
