# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run-relic-yatta

on:
  schedule:
    - cron:  '50 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd crawler
        pip install -r requirements.txt
    - name: Run
      run: |
        cd ${GITHUB_WORKSPACE}/crawler
        python relic_list.py
        echo '------------------------------------------------'
        for c in $(cat yatta/lib/reliclist.json | jq -r '.data[]|select(.spoiler==true)|.id'); do
          python relic_yatta.py ${c,,}
          echo '------------------------------------------------'
        done
    - name: Check result
      run: |
        if [ -d crawler/yatta ]; then
          tree crawler/yatta
          cp -r crawler/yatta/* ./
        fi
        r=$(git diff --exit-code . || echo)
        [ -z "$r" ] && echo "no change" || exit 0
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        draft: false
        delete-branch: true
        base: main
        branch: update-relic-workflow-${{ github.run_id }}
        title: '[Update Relic] ${{ github.run_id }}'
