# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run-relic-yatta

on:
  schedule:
    - cron:  '50 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd crawler
        pip install -r requirements.txt
    - name: Run
      run: |
        cd ${GITHUB_WORKSPACE}/crawler
        tree
        for c in $(cat ../lib/reliclist.json| jq -r '.data[]|select(.spoiler==true)|.id'); do
          python relic_yatta.py ${c,,}
          echo '------------------------------------------------'
        done
    - name: Check result
      run: |
        cd ${GITHUB_WORKSPACE}/crawler
        [ -d yatta ] && tree yatta
        for c in $(cat ../lib/reliclist.json| jq -r '.data[]|select(.spoiler==true)|.id'); do
          echo -e "\033[32mdiff yatta/lib/relics/${c,,}.json ../lib/relics/${c,,}.json\033[0m"
          (diff yatta/lib/relics/${c,,}.json ../lib/relics/${c,,}.json) || true
          echo '------------------------------------------------'
        done
        exit 0
